### ISSUE TITLE
Error: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by Zainulabadeen** [gagginaspinnata/tutsplus-downloader#11]
Please help me I am getting this error.

```
Traceback (most recent call last):
  File "download.py", line 4, in <module>
    from Tutsplus import Tutsplus
  File "C:\Users\Avaib\tutsplus\Tutsplus.py", line 60
    print "[+] Downloading " + video['titolo']

SyntaxError: Missing parentheses in call to 'print'

```

**Comment by a-eid** [comment]
run script with python version 2 not 3
